# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-03 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaddata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
