# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-03 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('pub_date', models.DateTimeField(auto_created=True, verbose_name='发布时间')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
