# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_blogapp2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogApp2',
        ),
    ]
