# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-22 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
