# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-19 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20160718_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
