# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-19 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_person_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels', people.models.ListField()),
            ],
        ),
    ]
