# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20160728_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
