# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0003_delete_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arc_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=255)),
                ('content', models.TextField(default='')),
            ],
        ),
    ]
